name: flutter_project_gen
description: A new Flutter package project.
version: 1.0.0+1
homepage: https://github.com/rodydavis/project_gen

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reflected_mustache: ^1.0.11
  freezed_annotation: ^0.7.1
  recase: ^3.0.0
  archive: ^2.0.13
  image_resizer: ^1.0.2
  path: ^1.7.0
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_version: ^2.0.0
  freezed: ^0.10.2
  settings_gen: ^1.0.4
  build_runner: ^1.7.1

flutter:
